### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by dkhgh** [Miragecoder/Urbanization#1]

**Comment by Miragecoder** [comment]
~~Having absolutely no experience with Mono, it absolutely does not seem like a challenge far too big! The biggest issue is obviously the 'SharpDX'-based renderer, but that's been an optional feature from the start!~~

~~If you're interested you could try give it a go yourself? I'm curious about the results! I might be wrong, but shouldn't it just be a matter of installing the mono run-time and the latest build?~~ 

Edit: Just gave it a spin myself; it works with the Mono run-time on Windows. The only things that are (obviously) broken are the 'SharpDx'-based renderer and the charting controls.

Mono run-time:
http://www.mono-project.com/download/

Latest build is available here:
https://ci.appveyor.com/project/Miragecoder/urbanization/build/artifacts

![image](https://cloud.githubusercontent.com/assets/3909841/8267106/0b9535c8-1754-11e5-9fc7-26e83bb19aa0.png)

**Comment by Miragecoder** [comment]
I'm going to go with mono support. (And try to come up with an elegant 'bundle package'-solution eventually) Refer to 'mono support'-labeled issues to see its support status.
